# =============================================================================
# Nginx Install Role: Handlers
# =============================================================================

---
# -----------------------------------------------------------------------------
# Reload Nginx Configuration
# -----------------------------------------------------------------------------
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true

# -----------------------------------------------------------------------------
# Restart Nginx Service
# -----------------------------------------------------------------------------
- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true
